# Application Configuration

# Database file record id on Zenodo
project_data:
  record_id: "3887306"
  file_name: "building-data-genome-project-2-v1.0.zip"
  raw_data_file_path: "./data_sources/raw_data"
  zip_file_folders_to_extract: ['raw', 'metadata', 'weather']
  schemas_dir_path: "./schemas"
  temp_dir_path: "./tmp"
  unique_columns: {'metadata': ['building_id'],
                   'weather': ['timestamp', 'site_id'],
                   'raw': ['timestamp', 'building_id', 'meter']}

logging:
  log_file_name: 'application.log'
  log_file_path: './logs'

ssl:
  ssl_cert_path: "cert.pem"
  postgresql_conf : "C:/Program Files/PostgreSQL/17/data/postgresql.conf"
  pg_hba_conf : "C:/Program Files/PostgreSQL/17/data/pg_hba.conf"

postgre_database:
  host: "localhost"
  port: 5432
  database: "building_energy_db_v2"
  user: "postgres"
  password: "postgres"

postgre_default_database:
  host: "localhost"
  port: 5432
  database: "postgres"
  user: "postgres"
  password: "postgres"

mongo_db_database:
  host: "localhost"
  port: 27017
  database: "building_energy_db_v2"

mong_db_user:
  admin:
    username: "admin"
    password: "admin"
  user_user:
    username: "user"
    password: "user"

